version: "3.7"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: books_db
      TZ: Europe/Bucharest
      PGTZ: Europe/Bucharest
    ports:
      - "12345:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./migrations/_init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local
